# Generated by Django 5.2 on 2025-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('character_class', models.CharField(max_length=50, verbose_name='Класс')),
                ('race', models.CharField(max_length=50, verbose_name='Раса')),
                ('role', models.CharField(choices=[('Tank', 'Танк'), ('Healer', 'Хилер'), ('DPS', 'ДД')], max_length=10, verbose_name='Роль')),
                ('server', models.CharField(max_length=100, verbose_name='Сервер')),
            ],
        ),
    ]
