# Generated by Django 5.2 on 2025-08-05 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecharacter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamecharacter',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве'), ('banned', 'Запрещён в мире')], default='active', max_length=10, verbose_name='Статус персонажа'),
        ),
        migrations.AddField(
            model_name='gamecharacter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='character_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='role',
            field=models.CharField(blank=True, choices=[('Tank', 'Танк'), ('Healer', 'Хилер'), ('DPS', 'ДД')], max_length=10, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='server',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сервер'),
        ),
    ]
